#!/bin/bash

if [ ! -f "/minecraft/minecraft-server-1.8.3.jar" ]; then
	cp /minecraft-install/minecraft-server-1.8.3.jar /minecraft
fi

cd /minecraft
java -Xmx1024M -Xms1024M -jar minecraft-server-1.8.3.jar nogui

